404 nf challenge
susird/404-not-found pull request #2
Opened 2021-04-10 19:00 UTC by susird

New pr for 404 not found challenge :sparkle:

2021-04-10 21:08 UTC, josepplloo requested changes
Very good job 👏 
the changes are about, missing html5 tags, unused classes, and missing/excess styles,
the styles will change, for that reason, I did no put any comments by now...
- try not to use margin properties, first try to solve the issues whit padding!
- if you have 2 o more margins/padding you will use margin property
eg
 ```
    margin-left: 735px;
    margin-top: 265px;
 ```
 === `margin: 265px 0 735px`
  use flex/grid
   - if you have `padding: 0px 0px 24px 0px;` use `padding-bottom: 24px ;` 
   - Pick only one between `px` and `em` (px)
   - don't use decimal `220.35px` -> 220px

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +  <div class="main">
Is more useful to have several semantic elements that define the different parts of a web page instead classes, change 
```
<div class="main">
```
for
```
<header >
```

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +    <div class="not-found">
this `div` is not necessary,  instead use flex/grid for your layout

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +      <h1 class="letter-not-found">404 not found</h1>
`letter-not-found` is not a useful name for this, try `title` or a different Block/Element name

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +  <div class="body">
could be `<section>`?

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +    <div class="scarecrow"></div>
you miss accesibility `<div role="img" aria-label="Description of the overall image">`

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +      <h1 class="bad-news"> I have bad news for you</h1>
delete white space and you don't have to wrapped this element, also consider rewriting "bad-news-title" class name for `bad-news-container` idem:
"phar-info"
"information"
"button"
"credits"
"credits-creator"
classes

2021-04-10 21:08 UTC, josepplloo commented on index.html
> +  <div class=" footer">
delete white space and use `<footer>` instead of  ` <div class=" footer">`

2021-04-10 21:47 UTC, anyruizd commented on index.html
> +  <link rel="preconnect" href="https://fonts.gstatic.com">
Do you need both of them?

2021-04-10 21:49 UTC, anyruizd commented on index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
Are you using the italic variation of the font somewhere? If not, you can delete it 
```suggestion
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@0,400;0,700;1,400;1,700&display=swap"
```

2021-04-10 22:00 UTC, anyruizd commented on style.css
> +    font-family: Space Mono;
You're declaring this `font-family` in many places that are not needed, you should import it just in the outer container of the elements that are using it. You should be using only three font-family definitions, as in the picture. The elements inside the container should inherit the font of their parents.
![image](https://user-images.githubusercontent.com/29681222/114285597-05af4100-9a1e-11eb-975a-4ce80583f9fa.png)

2021-04-10 22:02 UTC, anyruizd commented on style.css
> +  }
This media query shouldn't be here, in CSS all media queries go at the bottom of the stylesheet.

2021-04-10 22:06 UTC, anyruizd commented on style.css
> +  }
Why this selector only has one property? and why not put that property in the `.bad-news-title` selector? Also, is the title the `h1` element or its container? Why name it the other way around?

2021-04-10 22:08 UTC, anyruizd commented on style.css
> +  }
Please ident everything inside the media query

2021-04-10 22:09 UTC, anyruizd commented on style.css
> +  }
same question as in [bad-news ](https://github.com/susird/404-not-found/pull/2/files#r611098885)here

2021-04-10 22:10 UTC, anyruizd commented on style.css
> +  .phar-info {
This class name is not meaningful 🤔

2021-04-20 13:22 UTC, josepplloo requested changes
nice! now looks better but you miss footer

2021-04-20 13:22 UTC, josepplloo commented on index.html
> +</html>
👀 insert blank line

2021-04-20 13:22 UTC, josepplloo commented on index.html
> +   <article class="child-2-container">
ident this

2021-04-20 13:22 UTC, josepplloo commented on style.css
> +  letter-spacing: -0.090em;
use px

2021-04-20 13:24 UTC, josepplloo commented on style.css
> +.child-2-container {
you miss display: flex prop

2021-04-20 23:09 UTC, anyruizd approved these changes
I think you don't need this file anymore scarecrow.png. Other than that, it looks good to me

2021-04-24 20:05 UTC, josepplloo approved these changes
lgtm 💅

2021-04-25 00:23 UTC, merged